### PR TITLE
Fix issue #9 (Internal representation change in 1.16.4)

### PR DESCRIPTION
**Pull request by elgbar**
Due to internal change (caused by bug squashing) the `pages` field in `CraftMetaBook` is now nullable. Generally how pages are added internally was changed to use the protected function `internalAddPage` (see line 294 in [CraftMetaBook](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/560b65c4f8a15619aaa4a1737c7040f21e725cce#src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaBook.java)). This will be used instead of a normal add to the underlying list.

The update will also validate the length of the json input. However if this is done when setting the pages it might result in invalid json, and consequently plain text. Thus this patch does not validate the length of the input.

See [CraftBukkit commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/560b65c4f8a15619aaa4a1737c7040f21e725cce)

This has been tested on paper [1.16.4-355](https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/355/downloads/paper-1.16.4-355.jar) and [paper-1.16.4-396](https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/396/downloads/paper-1.16.4-396.jar). The first is before the mentioned CraftBukkit commit while the second is the latest version as of writing (and of course after the internal changes).

### CODE REVIEW

**Comment by SnowyCoder** [comment]
Thanks for your work, the code seems perfect and the link explains everything.
Just one question, why did you use `internalAddPage` instead of `addPage`? I mean, is there a particular reason?

**Comment by elgbar** [comment]
>  why did you use `internalAddPage` instead of `addPage`? I mean, is there a particular reason

Yes, in `addPage` the content is truncated after `MAX_PAGE_LENGTH` chars. Which breaks when writing longer/complicated pages.

**Comment by elgbar** [comment]
Note that the latest commit changes how null pages are handled. Before an exception would be thrown. Now it is parsed as an empty page.

**Comment by SnowyCoder** [comment]
> > why did you use `internalAddPage` instead of `addPage`? I mean, is there a particular reason
> 
> Yes, in `addPage` the content is truncated after `MAX_PAGE_LENGTH` chars. Which breaks when writing longer/complicated pages.

Now I'm confused on why does the spigot implementation do it, but it's consistent with the older implementation.

> Note that the latest commit changes how null pages are handled. Before an exception would be thrown. Now it is parsed as an empty page.

Thanks, I missed it.

Ok, the code is well documented (you also fixed some of the old javadoc), I tested on both newer and older version and it works.
So it should be fine, I'll deploy the new version to maven as soon as I can. Thank you!

**Pull request merged**
